### ISSUE TITLE
Brazilian server connection

### ISSUE THREAD

**Issue by rffontenelle** [chaosk/teerace#263]
Hello, there. I'm sponsor of the "Teerace Brasil" server and I was told the server's Teerace instances are online, but are not connected with the Teerace webapp. It was suggested a problem with API token.

Can someone please let me know what I need to do to get it connected again? 

p.s.: Sorry if this is not the appropriate way to contact about it. I tried joining [#teerace](https://webchat.quakenet.org/?channels=teerace) IRC channel, as suggestion in [Help page](http://race.teesites.net:80/help/#how-can-i-host-teerace-server), but the room is empty.

**Comment by SushiTee** [comment]
Hi, well all those information are quite outdated. How did you get to the help page? The website isn't online at all. The same is true for the API. Teerace is offline.
We are currently making everything new but it may take some time before it's finished.

The irc channel is dead. Instead there is a discord channel.

**Comment by rffontenelle** [comment]
> Hi, well all those information are quite outdated. How did you get to the help page? The website isn't online at all.

Using Wayback Machine website (https://web.archive.org) and accessing the last valid snapshot - from Feb 2018, a think.

> The same is true for the API. Teerace is offline. We are currently making everything new but it may take some time before it's finished.

I see. I thought it was a problem on my server and the website was just a bad SSL configuration ("ERR_SSL_PROTOCOL_ERROR").  Thanks for the info.

I'd be interested in be aware of the status up of Teerace, so the Brazilian server can be up too. What would be the best way of me being aware of it? Is there a announcement channel, do you have a way to contact me... ?

> 
> The irc channel is dead. Instead there is a discord channel.

Is this channel open for public? If yes, can you provide the name or an invite? Would be easier to talk about game instances' connection issues, status, etc.

**Comment by SushiTee** [comment]
The channel is not public as far as I know. Find a way how I can contact you and I'll send you an invite.

**Comment by rffontenelle** [comment]
Can you send to discord user `@RafaelFF#0533`

**Comment by SushiTee** [comment]
added you

**Comment by rffontenelle** [comment]
Great, thanks. Closing this.
